### ISSUE TITLE
Preview 8 Update?

### ISSUE THREAD

**Issue by Redeye51** [Mewriick/Blazor.GoogleMap#1]
First I want to say thanks for creating this component.  Is development continuing? I was wondering if there was going to be an update for the .net core preview 8

Thanks!

**Comment by Redeye51** [comment]
Has this project been abandoned?

**Comment by ardacetinkaya** [comment]
I just requested a PR for final ASP.NET Core 3.0 support and examples

@Mewriick could you please review PR and give an update about the project?

#2

**Comment by Mewriick** [comment]
I had some traveling holidays, and also I have another project for Blazor and also day work, so I have to prioritize features for this project. Also maybe community can help with this and propse some features which you want to see in this component.

Thnaks a lot for your feeback!
